/**
 * lib/content/types.ts
 * --------------------
 * Re-exports TypeScript types inferred from velite schemas.
 * These are the canonical entry-record types for the entire site.
 *
 * Owner: Procyon (α-IDX-03)
 * Tasks: TASK-2026-05-15-22 / TASK-2026-05-15-30 / TASK-2026-05-17-PROCYON-WAVE1-BUNDLE
 *
 * Note: After velite build runs, types are also available from '.velite'.
 * This module re-exports them under stable names so consumers are insulated
 * from velite output path changes.
 */
import type {
  Article as VeliteArticle,
  Fiction as VeliteFiction,
  Photo as VelitePhoto,
  PhotoSidecar as VelitePhotoSidecar,
} from '../../.velite'

export type Article = VeliteArticle
export type Fiction = VeliteFiction
/** Roll-level descriptor record (roll.mdx). One per roll directory. */
export type Photo = VelitePhoto
/** Per-photo sidecar record (DSCF*.mdx). One per source JPEG with sidecar. */
export type PhotoSidecar = VelitePhotoSidecar

// ---------------------------------------------------------------------------
// Photo EXIF and variant types — TASK-30
// Canonical definitions consumed by Sirius (entry page) and Altair (NETRA tools).
// ---------------------------------------------------------------------------

/** EXIF metadata block. No GPS fields — stripped at process-photos.ts time. */
export type PhotoExif = {
  /** Camera make + model, e.g. "FUJIFILM X-E5". */
  camera?: string
  /** Lens model, e.g. "XF23mmF2 R WR". */
  lens?: string
  /** Fuji film simulation name, e.g. "Classic Chrome". Drives TASK-34 palette suggestion. */
  filmSim?: string
  /** Aperture as f-number, e.g. 2.8. */
  aperture?: number
  /** Shutter speed display string, e.g. "1/250". */
  shutter?: string
  /** ISO value, e.g. 400. */
  iso?: number
  /** Focal length in mm (native), e.g. 23. */
  focal?: number
  /** Focal length equivalent in 35mm, e.g. 35. */
  focal35?: number
  /** ISO 8601 capture time string. */
  captureTime?: string
}

/** A single format entry within a variant size. */
export type PhotoVariantEntry = {
  /** JPEG path, web-root relative. */
  jpg: string
  /** WebP path, web-root relative. */
  webp: string
  /** AVIF path, web-root relative. */
  avif: string
}

/**
 * Responsive variant set. Generated by scripts/process-photos.ts.
 * Three sizes × three formats = 9 output files per source JPEG.
 * Absent if process-photos.ts has not been run yet.
 */
export type PhotoVariants = {
  /** 320px wide. Thumbnails and contact sheet. */
  thumb: PhotoVariantEntry
  /** 1280px wide. Lightbox medium. */
  medium: PhotoVariantEntry
  /** 2400px wide. Full-resolution view. */
  full: PhotoVariantEntry
}

// ---------------------------------------------------------------------------
// Fiction branching types — TASK-2026-05-17-PROCYON-BRANCHING-SCHEMA
// Consumed by Sirius (§13.2 renderer) and Altair (NETRA branch-activation tools).
// Mirrors fictionVariantSchema in velite.config.ts — kept in sync manually.
// ---------------------------------------------------------------------------

/**
 * A single alternate-α variant for a fiction transmission.
 * Corresponds to one tendril in the NeX orbital branching cloud.
 * See 30-worldline-branching.md §3.1 (Channel A) + §4.3 (coordinate model).
 */
export type FictionVariant = {
  /** Divergence value of the alternate worldline. String to preserve decimal precision. */
  alpha: string
  /** One-line description of what diverges in this variant. Max 120 chars. NETRA reads this. */
  delta_summary: string
  /**
   * Optional explicit drift magnitude = |variant.alpha − site.alpha|.
   * If absent, the renderer derives it from alpha at render time.
   * §4.3: distance_i = R × (0.06 + min(delta_alpha_i × 60, 0.10))
   */
  drift?: number
  /**
   * Optional slug pointing to a materialized fiction file for this variant.
   * V1 renderer ignores this (v1 is read-only per §6.1).
   * Forward-compatible toward v1.1 hybrid interaction.
   */
  slug?: string
}

// ---------------------------------------------------------------------------
// Globe pin union — used by WorldlineGlobe.tsx via TASK-33
// ---------------------------------------------------------------------------

/**
 * A typed Globe pin record. Discriminated by `kind` so Sirius can render
 * different glyph shapes per content type (article=circle, photo=square,
 * fiction=diamond) per journey-arch §2.2.
 */
export type GlobePin =
  | ArticlePin
  | PhotoPin
  | FictionPin

export type ArticlePin = {
  kind: 'article'
  fileNum: string
  title: string
  summary: string
  coords: { lat: number; lon: number; place: string }
  /** ISO date for sort. */
  isoDate: string
  domain: string
  status: string
  tags: string[]
}

export type PhotoPin = {
  kind: 'photo'
  roll: string
  id: string
  caption?: string
  /** Only present when shareLocation=true AND coords are defined. */
  coords: { lat: number; lon: number; place: string }
  isoDate: string
  /** Film simulation from EXIF — for TASK-34 palette suggestion on hover. */
  filmSim?: string
  /** Thumbnail variant for Globe hover preview — uses variants.thumb.webp. */
  thumbWebp?: string
}

export type FictionPin = {
  kind: 'fiction'
  slug: string
  title: string
  summary: string
  /** Orbital placement is by meaning-coords (domain + date), not GPS.
   *  Globe placement algorithm lives in TASK-33 (WorldlineGlobe.tsx).
   *  We provide the domain + date so Sirius can compute NeX orbit coords. */
  domain: string
  isoDate: string
  tags: string[]
  /**
   * Alternate-α variant tendrils for this fiction node.
   * Empty array when no variants declared (the node branches only via siblings,
   * or not at all). Sirius reads this at RW-5 drift activation (§13.2 step 2).
   * 30-worldline-branching.md §3.1 (Channel A) + §4.3.
   */
  variants: FictionVariant[]
  /**
   * Divergence cluster label. Undefined when not declared.
   * Build-time sibling computation uses this to group fiction entries.
   * Sirius receives the pre-computed sibling list (getFictionSiblings) rather
   * than computing it in the renderer. 30-worldline-branching.md §3.1 (Channel B).
   */
  divergence_cluster?: string
}

// ---------------------------------------------------------------------------
// Worldline-weave types — S3 · VISION-2026-05-31 §2.1
// Consumed by lib/content/worldline.ts (helpers) + <WorldlineLinks /> (Sirius).
// Design spec: docs/design/16-worldline-schema.md §2
// ---------------------------------------------------------------------------

/**
 * A single outgoing inter-entry link, as declared in frontmatter.
 *
 * `to` format: "article/<fileNum>" | "fiction/<slug>" | "photos/<roll>/<id>"
 * `label` is optional free-text prose rendered in Cormorant italic at the arc-node.
 */
export type WorldlineLink = {
  to: string
  label?: string
}

/**
 * An incoming edge computed at build time by lib/content/worldline.ts.
 *
 * `from` is the full canonical key of the source entry ("article/003").
 * `fromKind` drives glyph selection in <WorldlineLinks />:
 *   article → circle · fiction → diamond · photo → square (journey-arch §2.2)
 * `label` is the label the SOURCE entry assigned to this link (may differ from
 *   the target's perspective — it's the author's framing of the relationship).
 */
export type WorldlineEdge = {
  from: string
  fromKind: 'article' | 'fiction' | 'photo'
  label?: string
}

/**
 * Full 1-hop neighbourhood for an entry.
 * Returned by lib/content/worldline.ts get1HopNeighborhood().
 * Consumed by <WorldlineLinks /> (Sirius) to render the §worldline section.
 *
 * Invariant: outgoing and incoming share no entries (different DAG directions).
 */
export type WorldlineNeighborhood = {
  outgoing: WorldlineLink[]
  incoming: WorldlineEdge[]
}

// ---------------------------------------------------------------------------
// MDX component prop types — TASK-2026-05-17-PROCYON-WAVE1-BUNDLE Task A
// Canonical prop interfaces for MDX components used in article body.
// Sirius (α-SUR-01) implements the rendering JSX; Procyon owns this interface.
// ---------------------------------------------------------------------------

/**
 * Props for the <Pullquote> MDX component.
 *
 * Re-exported from components/Pullquote.tsx for consumers who need the type
 * without importing from the component tree (e.g. mdx-components.ts, Storybook).
 *
 * Rendering spec (for Sirius):
 *   Quote body:
 *     · Cormorant Garamond italic · 24px · line-height 1.3
 *     · padding-left: 32px
 *     · left hairline: 1px solid var(--accent-orange)
 *     · color: var(--ink-primary)
 *
 *   source attribution (when present):
 *     · em-dash prefix: "— {source}"
 *     · JetBrains Mono · 11px desktop / 10px mobile
 *     · color: var(--ink-soft)
 *     · margin-top: var(--space-2)
 *
 * @see components/Pullquote.tsx
 * @see docs/design/09-article-entry.md §typography/pullquote
 */
export type { PullquoteProps } from '../../components/Pullquote'
