/**
 * lib/content/types.ts
 * --------------------
 * Re-exports TypeScript types inferred from velite schemas.
 * These are the canonical entry-record types for the entire site.
 *
 * Owner: Procyon (α-IDX-03) · TASK-2026-05-15-22 / TASK-2026-05-15-30
 *
 * Note: After velite build runs, types are also available from '.velite'.
 * This module re-exports them under stable names so consumers are insulated
 * from velite output path changes.
 */
import type {
  Article as VeliteArticle,
  Fiction as VeliteFiction,
  Photo as VelitePhoto,
  PhotoSidecar as VelitePhotoSidecar,
} from '../../.velite'

export type Article = VeliteArticle
export type Fiction = VeliteFiction
/** Roll-level descriptor record (roll.mdx). One per roll directory. */
export type Photo = VelitePhoto
/** Per-photo sidecar record (DSCF*.mdx). One per source JPEG with sidecar. */
export type PhotoSidecar = VelitePhotoSidecar

// ---------------------------------------------------------------------------
// Photo EXIF and variant types — TASK-30
// Canonical definitions consumed by Sirius (entry page) and Altair (NETRA tools).
// ---------------------------------------------------------------------------

/** EXIF metadata block. No GPS fields — stripped at process-photos.ts time. */
export type PhotoExif = {
  /** Camera make + model, e.g. "FUJIFILM X-E5". */
  camera?: string
  /** Lens model, e.g. "XF23mmF2 R WR". */
  lens?: string
  /** Fuji film simulation name, e.g. "Classic Chrome". Drives TASK-34 palette suggestion. */
  filmSim?: string
  /** Aperture as f-number, e.g. 2.8. */
  aperture?: number
  /** Shutter speed display string, e.g. "1/250". */
  shutter?: string
  /** ISO value, e.g. 400. */
  iso?: number
  /** Focal length in mm (native), e.g. 23. */
  focal?: number
  /** Focal length equivalent in 35mm, e.g. 35. */
  focal35?: number
  /** ISO 8601 capture time string. */
  captureTime?: string
}

/** A single format entry within a variant size. */
export type PhotoVariantEntry = {
  /** JPEG path, web-root relative. */
  jpg: string
  /** WebP path, web-root relative. */
  webp: string
  /** AVIF path, web-root relative. */
  avif: string
}

/**
 * Responsive variant set. Generated by scripts/process-photos.ts.
 * Three sizes × three formats = 9 output files per source JPEG.
 * Absent if process-photos.ts has not been run yet.
 */
export type PhotoVariants = {
  /** 320px wide. Thumbnails and contact sheet. */
  thumb: PhotoVariantEntry
  /** 1280px wide. Lightbox medium. */
  medium: PhotoVariantEntry
  /** 2400px wide. Full-resolution view. */
  full: PhotoVariantEntry
}

// ---------------------------------------------------------------------------
// Globe pin union — used by WorldlineGlobe.tsx via TASK-33
// ---------------------------------------------------------------------------

/**
 * A typed Globe pin record. Discriminated by `kind` so Sirius can render
 * different glyph shapes per content type (article=circle, photo=square,
 * fiction=diamond) per journey-arch §2.2.
 */
export type GlobePin =
  | ArticlePin
  | PhotoPin
  | FictionPin

export type ArticlePin = {
  kind: 'article'
  fileNum: string
  title: string
  summary: string
  coords: { lat: number; lon: number; place: string }
  /** ISO date for sort. */
  isoDate: string
  domain: string
  status: string
  tags: string[]
}

export type PhotoPin = {
  kind: 'photo'
  roll: string
  id: string
  caption?: string
  /** Only present when shareLocation=true AND coords are defined. */
  coords: { lat: number; lon: number; place: string }
  isoDate: string
  /** Film simulation from EXIF — for TASK-34 palette suggestion on hover. */
  filmSim?: string
  /** Thumbnail variant for Globe hover preview — uses variants.thumb.webp. */
  thumbWebp?: string
}

export type FictionPin = {
  kind: 'fiction'
  slug: string
  title: string
  summary: string
  /** Orbital placement is by meaning-coords (domain + date), not GPS.
   *  Globe placement algorithm lives in TASK-33 (WorldlineGlobe.tsx).
   *  We provide the domain + date so Sirius can compute NeX orbit coords. */
  domain: string
  isoDate: string
  tags: string[]
}
